name: Run MATLAB Script on GitHub-Hosted Runner
on:
  schedule:
    - cron: 0/10 * * * *
  push:
    branches:
      - master
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Setup path
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("scripts");
      - name: Setup path
        uses: ./
        with:
          command: covid_patients;